name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  deploy-docs:
    name: Update Documentation
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build Javadocs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javadoc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc
          destination_dir: ${{ github.event.release.tag_name }}